<main class="history">
	<section>
		<h1 class="history-title js-history-title"></h1>
			<div class="aboutusagency">	
					
				<!-- Slideshow container -->
				<div class="slideshow-container">
					<?php foreach($aboutSlider as $aboutSlide): ?>
						  <div class="mySlides fade">
						    <img src="<?= htmlspecialchars($aboutSlide['src']) ?>" alt="<?= htmlspecialchars($aboutSlide['alt']) ?>">
						  </div>
					<?php endforeach; ?>
				  
				  <!-- Next and previous buttons -->
				  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
				  <a class="next" onclick="plusSlides(1)">&#10095;</a>
			    </div>
				<p class="history-about"><?= htmlspecialchars($aboutus['history']) ?></p>
			</div>	
	</section>	
				
</main>

