<main class="add-footer-neetwork">
	<section class="add-footer-network">
		<h2>Add Footer Network</h2>
			<form method="post" enctype="multipart/form-data"> 
				<p>
					<label for="networkUrl">URL of the Network :</label>
				</p>
				<p>
					<input type="text" name="networkUrl" id="networkUrl" value=" "/>
				</p>
				<p>
					<label for="nameNetwork">Name of the Network :</label>
				</p>
				<p>
					<select name="nameNetwork" id="nameNetwork">
					    <?php foreach($Networkname as  $Networknam): ?>
		                <option value="<?= htmlspecialchars($Networknam['id']) ?>"><?= htmlspecialchars($Networknam['name_network']) ?></option>
		                <?php endforeach; ?>
		            </select>
				</p>
					<button class="button-title" type="submit">Add</button>
			</form>
	</section>
</main>
