<main class="add-new-network-service">
	
		<section class="add-new-network-service">	
			<h2>Add new network service</h2>
			<form method="post" enctype="multipart/form-data"> 
					<p>
						<label for="Service">Choose Service</label>
					</p>
					<p>
						<select name="Service" id="Service">
		    			    <?php foreach($services as  $service): ?>
			                <option value="<?= htmlspecialchars($service['id']) ?>"><?= htmlspecialchars($service['title']) ?></option>
			                <?php endforeach; ?>
			            </select>
					</p>
					<p>
						<label for="nameNetwork">Choose name network</label>
					</p>
					<p>
							<select name="nameNetwork" id="nameNetwork">
							    <?php foreach($Networkname as  $Networknam): ?>
				                <option value="<?= htmlspecialchars($Networknam['id']) ?>"><?= htmlspecialchars($Networknam['name_network']) ?></option>
				                <?php endforeach; ?>
				            </select>
					</p>
					<p>	
						<label for="network">Add network</label> 
					</p>
					<p>
						<input type="text" name="network" id="network" value=""/>
					</p>
				
					<button class="button-title" type="submit">Add</button>
			</form>
		</section>

</main>
