<main class="add-slider-about">
	<section class="add-slider-about">">
		<h2>Add photo to slider About </h2>
			<form method="post" enctype="multipart/form-data">
				<p>
					<label for='image'>Foto</label>
				</p>
				<p>
					<input type="file" name="image" id="image">
					<input type="hidden" name="imageBdd" id="imageBdd" value=""/>
				</p>
				<p>	
					<label for="nameImage">Name of the foto</label> 
				</p>
				<p>
					<input name="nameImage" id="nameImage"/>
				</p>
				<button class="button-add" type="submit">Add</button>
			</form>
	</section>
</main>		
		