<main class="admin">
	<section class="admin">
		<form  method="post">
			<p>
				<label class="admin" for='login'>Login</label>
			</p>
			<p class="admin">
				<input type="text" name="login" id="login">
			</p>
				<p><?= $this -> message1 ?></p>
			<p >
				<label class="admin" for='pw'>Password</label>
			</p>
			<p class="admin">
				<input type="password" name="pw" id="pw">
			</p>
				<p><?= $this -> message2 ?></p>
		
			<button class="button-contact" type="submit">Connect</button>
		</form>
	</section>	
</main>
