<main class="dashboard">
    <section class="dashboard-section">
        <h2>Dashboard</h2>
            <nav class="dashboard">
                <table>
                    <tr>
                        <td><a href="modifyaboutus">About us</a></td>
                    </tr>
                    <tr>
                        <td><a href="modifservices">Services</a></td>
                    </tr> 
                    <tr>
                        <td><a href="modifyblog">Blog</a></td>
                    </tr> 
                    <tr>
                        <td><a href="modifyfooter">Footer</a></td>
                    </tr>
                    <tr>
                        <td><a href="modifycontact">Contact us</a></td>
                    </tr>
                     <tr>
                        <td><a href="modifyadmin">Admin</a></td>
                    </tr>
                </table>
            </nav>
    </section>
</main>
