<main class="modify-type-service">
	<section class="modify-type-service">	
		<h2>Modify pass</h2>
		<form method="post" enctype="multipart/form-data"> 
			<p>
				<label class="admin" for='pw'>Password</label>
			</p>
			<p class="admin">
				<input type="password" name="pw" id="pw" value="<?= htmlspecialchars($pass['password']) ?>">
			</p>
			<button class="button-title" type="submit">Change</button>
		</form>
	</section>
</main>
