<main class="show-all-comments">
    <section  class="show-all-comments">
       	<h2>List of the comments: <?= htmlspecialchars($commentsnb['nb']) ?></h2>
            <table>
                <tr>
                    <th>Title of Article</th>
                    <th>Comments</th>
                    <th>Name</th>
                    <th>Date of creation</th>
                    <th>Delete</th>
                </tr>
                <?php foreach($commentes as $commente): ?>
                <tr>
                   	<td><?= htmlspecialchars($article['title']) ?></td>
                    <td><?= htmlspecialchars($commente['comment']) ?></td>
                    <td><?= htmlspecialchars($commente['name']) ?></td>
                    <td><?= htmlspecialchars($commente['date_comment']) ?></td>
                    <td><a class="clickdelete js-confirm-button" data-url="index.php?page=deletecomments&id=<?= htmlspecialchars($commente['id']) ?>"><i class="fas fa-trash-alt"></i></a></td>
                </tr>
               <?php endforeach; ?>
            </table>
    </section>
</main>
