<main class="modifFooter-network">
	<section class="modifFooter-network">
	<h2>Modify Footer Network</h2>
	    <form method="post" enctype="multipart/form-data"> 
			<p>
				<label for="nameNetwork">Name of the Network:</label>
			</p>
			<p>
				<select name="nameNetwork" id="nameNetwork">
					 <option value="">--Please choose new name Network--</option>
				<?php foreach($Networkname as  $Networknam): ?>
	                <option value="<?= htmlspecialchars($Networknam['id']) ?>"><?= htmlspecialchars($Networknam['name_network']) ?></option>
	            <?php endforeach; ?>
	            </select>
			</p>
			<p>
				<label for="networkUrl">URL of the Network :</label>
			</p>
			<p>
				<input type="text" name="networkUrl" id="networkUrl" value="<?= htmlspecialchars($NetworkId['url'])?>"/>
			</p>
				<button class="button-title" type="submit">Change</button>
		</form>
	</section>
</main>
