<main class="modify-type-service">
	<section class="modify-type-service">	
		<h2>Modify type of service</h2>
		<form method="post" enctype="multipart/form-data"> 
			<p>	
				<label for="list_services">Modify type of service</label> 
			</p>
			<p>
				<input type="text" name="list_services" id="list_services" value="<?= htmlspecialchars($service['services']) ?>"/>
			</p>
			<button class="button-title" type="submit">Change</button>
		</form>
	</section>
</main>
